### ISSUE TITLE
Modificar el modelo de Empresas

### ISSUE THREAD

**Issue by AMDevelopOB** [OpenDevs-Beta/backAPI#3]
- Empresa:  
    - Añadir ‘url’ (web de la empresa)
    - ¿Creación debería ser una fecha?
    - Avatar/imagen
    - Sector
    - Persona contacto (esto será solo para admins)
    - Teléfono de contacto (esto será solo para admins)
    - Email contacto (esto será solo para admins)

Revisar la info que se manda en los endpoints y proponer como securizarlos.

**Comment by AMDevelopOB** [comment]
Buenas Victor, has completado la tarea? No he visto ningun pull request a la rama dev, has subido tu rama?

**Comment by victorcanash** [comment]
Nada, que sin querer le he dado a cerrarla y la he vuelto a abrir

**Comment by victorcanash** [comment]
Rutas con middleware auth (api tokens) y con roles: [user, admin]
	Rutas users: si eres el mismo usuario puedes acceder a update, delete.
	Rutas empresas y ofertas: si eres el creador puedes acceder a update, delete.
	Si eres admin puedes acceder a cualquier ruta

**Comment by AMDevelopOB** [comment]
Bastante bien Victor. 

Vamos a tener en cuenta unos detalles. Al estar ya la base de datos creada en producción, si modificamos el archivo de migración, no va a surtir ningún efecto, por lo que es recomendable crear una migración nueva, pero en este caso en lugar de usar createTable, usaríamos "alterTable".

Por lo demás me parece correcto el modelo, y me parece correcto el planteamiento de los middlewares. Investiga un poco más acerca de los bouncer. 

Esta tarde te asignaré una nueva tarea. Buen trabajo.
